const poemData = [
    { text: "伯牙", py: "bó yá", zh: "伯牙，春秋时期著名的琴师，善于弹琴。", en: "Boya" },
    { text: "善", py: "shàn", zh: "动词/副词，擅长，长于。", en: "was good at", exam: true },
    { text: "鼓", py: "gǔ", zh: "动词，弹奏（弦乐器）。", en: "playing", exam: true },
    { text: "琴", py: "qín", zh: "古琴，一种传统的弦乐器。", en: "the zither," },
    { text: "，", punc: true },
    { text: "钟子期", py: "zhōng zǐ qī", zh: "钟子期，春秋时期著名的听众，伯牙的知音。", en: "Zhong Ziqi" },
    { text: "善", py: "shàn", zh: "副词，擅长，精通。", en: "was good at" },
    { text: "听", py: "tīng", zh: "动词，聆听，倾听并理解。", en: "listening." },
    { text: "。", punc: true },
    { text: "伯牙", py: "bó yá", zh: "伯牙。", en: "When Boya" },
    { text: "鼓", py: "gǔ", zh: "弹奏。", en: "played" },
    { text: "琴", py: "qín", zh: "古琴。", en: "the zither," },
    { text: "，", punc: true },
    { text: "志", py: "zhì", zh: "名词用作动词，心里想到，心意在……", en: "his mind" },
    { text: "在", py: "zài", zh: "在。", en: "was on" },
    { text: "高山", py: "gāo shān", zh: "巍峨的大山。", en: "high mountains," },
    { text: "，", punc: true },
    { text: "钟子期", py: "zhōng zǐ qī", zh: "钟子期。", en: "Zhong Ziqi" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "善", py: "shàn", zh: "形容词，好啊，赞叹词。", en: "How wonderful!", exam: true },
    { text: "哉", py: "zāi", zh: "文言语气词，表感叹，相当于“啊”。", en: "" },
    { text: "，", punc: true },
    { text: "峨峨", py: "é é", zh: "形容词，高耸的样子，巍峨的样子。", en: "Lofty and high" },
    { text: "兮", py: "xī", zh: "文言语气词，相当于“啊”或“呀”。", en: "" },
    { text: "若", py: "ruò", zh: "动词，好像，如同。", en: "like", exam: true },
    { text: "泰山", py: "tài shān", zh: "泰山，中国著名的五岳之首。", en: "Mount Tai!" },
    { text: "！", punc: true },
    { text: "”", punc: true },
    { text: "志", py: "zhì", zh: "心意，心里想到。", en: "When his mind" },
    { text: "在", py: "zài", zh: "在。", en: "was on" },
    { text: "流水", py: "liú shuǐ", zh: "奔腾的江河流水。", en: "flowing water," },
    { text: "，", punc: true },
    { text: "钟子期", py: "zhōng zǐ qī", zh: "钟子期。", en: "Zhong Ziqi" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "善", py: "shàn", zh: "好啊。", en: "How wonderful!" },
    { text: "哉", py: "zāi", zh: "感叹语气词。", en: "" },
    { text: "，", punc: true },
    { text: "洋洋", py: "yáng yáng", zh: "形容词，水势浩荡的样子。", en: "Vast and wide" },
    { text: "兮", py: "xī", zh: "语气词。", en: "" },
    { text: "若", py: "ruò", zh: "好像，如同。", en: "like" },
    { text: "江河", py: "jiāng hé", zh: "长江和黄河，泛指大江大河。", en: "the great rivers!" },
    { text: "！", punc: true },
    { text: "”", punc: true },
    { text: "伯牙", py: "bó yá", zh: "伯牙。", en: "Whatever Boya" },
    { text: "所", py: "suǒ", zh: "特殊助词，“所”字结构，与动词结合表示人或事。", en: "was" },
    { text: "念", py: "niàn", zh: "动词，心里想到的，思考的。", en: "thinking of," },
    { text: "，", punc: true },
    { text: "钟子期", py: "zhōng zǐ qī", zh: "钟子期。", en: "Zhong Ziqi" },
    { text: "必", py: "bì", zh: "副词，一定，必然。", en: "would always" },
    { text: "得", py: "dé", zh: "动词，领会，理解，明白。", en: "understand", exam: true },
    { text: "之", py: "zhī", zh: "代词，指代伯牙心中所想的心意、心境。", en: "it." },
    { text: "。", punc: true },
    { text: "子期", py: "zǐ qī", zh: "钟子期。", en: "After Ziqi" },
    { text: "死", py: "sǐ", zh: "去世，逝世。", en: "died," },
    { text: "，", punc: true },
    { text: "伯牙", py: "bó yá", zh: "伯牙。", en: "Boya" },
    { text: "谓", py: "wèi", zh: "动词，认为，说。", en: "thought that" },
    { text: "世", py: "shì", zh: "名词，世界上，世上。", en: "the world" },
    { text: "再", py: "zài", zh: "副词，再也，重新。", en: "no longer had" },
    { text: "无", py: "wú", zh: "没有。", en: "" },
    { text: "知音", py: "zhī yīn", zh: "名词，真正懂得自己音乐心境的挚友。", en: "a soulmate who understood his music." },
    { text: "，", punc: true },
    { text: "乃", py: "nǎi", zh: "副词，于是，就。", en: "Therefore, he", exam: true },
    { text: "破", py: "pò", zh: "动词，砸碎，摔破。", en: "smashed" },
    { text: "琴", py: "qín", zh: "古琴。", en: "the zither" },
    { text: "绝", py: "jué", zh: "动词，割断，斩断。", en: "and cut", exam: true },
    { text: "弦", py: "xián", zh: "琴弦。", en: "its strings," },
    { text: "，", punc: true },
    { text: "终身", py: "zhōng shēn", zh: "名词，一辈子，一辈子到老。", en: "and for the rest of his life" },
    { text: "不", py: "bù", zh: "不再。", en: "never" },
    { text: "复", py: "fù", zh: "副词，再，重新。", en: "again", exam: true },
    { text: "鼓", py: "gǔ", zh: "动词，弹琴。", en: "played it." },
    { text: "。", punc: true }
];
